import mongoose from 'mongoose';
import userModel from '../models/userModel.js';
import DBconnect from './massproject.js';

// const connectDB = async ()=>{
//     mongoose.connection.on('connected', ()=>console.log('Database Connected'));

//     await mongoose.connect(process.env.MONGODB_URI);
// };

const students = [
    {
      rollNo: 477,
      name:"Shiwans Vaishya",
      email: "g22.shiwans.vaishya@gnkhalsa.edu.in",
      role:"student",
      department:"CS",
      batch:"Batch3",
      year:"2024-2025"
    },
    {
      rollNo: 421,
      name:"Dev Ghildiyal",
      email: "g22.dev.ghildiyal@gnkhalsa.edu.in",
      role:"student",
      department:"CS",
      batch:"Batch1",
      year:"2024-2025"
    },
    {'rollNo': 482,
      'name': 'Aditya Gupta',
      'email': 'g22.aditya.gupta@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'IT',
      'batch': 'Batch2',
      'year': '2025-2026'},
     {'rollNo': 466,
      'name': 'Rohan Singh',
      'email': 'g22.rohan.singh@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'IT',
      'batch': 'Batch3',
      'year': '2025-2026'},
     {'rollNo': 477,
      'name': 'Kabir Reddy',
      'email': 'g22.kabir.reddy@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'CS',
      'batch': 'Batch2',
      'year': '2025-2026'},
     {'rollNo': 470,
      'name': 'Vivaan Singh',
      'email': 'g22.vivaan.singh@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'CS',
      'batch': 'Batch1',
      'year': '2024-2025'},
     {'rollNo': 446,
      'name': 'Krishna Singh',
      'email': 'g22.krishna.singh@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'IT',
      'batch': 'Batch3',
      'year': '2024-2025'},
     {'rollNo': 442,
      'name': 'Aditya Das',
      'email': 'g22.aditya.das@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'IT',
      'batch': 'Batch3',
      'year': '2025-2026'},
     {'rollNo': 427,
      'name': 'Ishaan Reddy',
      'email': 'g22.ishaan.reddy@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'CS',
      'batch': 'Batch3',
      'year': '2024-2025'},
     {'rollNo': 404,
      'name': 'Vivaan Patel',
      'email': 'g22.vivaan.patel@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'CS',
      'batch': 'Batch1',
      'year': '2025-2026'},
     {'rollNo': 433,
      'name': 'Vivaan Gupta',
      'email': 'g22.vivaan.gupta@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'IT',
      'batch': 'Batch1',
      'year': '2024-2025'},
     {'rollNo': 494,
      'name': 'Om Verma',
      'email': 'g22.om.verma@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'CS',
      'batch': 'Batch2',
      'year': '2024-2025'},
     {'rollNo': 400,
      'name': 'Atharv Patel',
      'email': 'g22.atharv.patel@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'IT',
      'batch': 'Batch2',
      'year': '2024-2025'},
     {'rollNo': 420,
      'name': 'Atharv Mishra',
      'email': 'g22.atharv.mishra@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'CS',
      'batch': 'Batch3',
      'year': '2025-2026'},
     {'rollNo': 410,
      'name': 'Kabir Sharma',
      'email': 'g22.kabir.sharma@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'CS',
      'batch': 'Batch2',
      'year': '2024-2025'},
     {'rollNo': 456,
      'name': 'Kabir Patel',
      'email': 'g22.kabir.patel@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'IT',
      'batch': 'Batch3',
      'year': '2025-2026'},
     {'rollNo': 468,
      'name': 'Ishaan Patel',
      'email': 'g22.ishaan.patel@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'CS',
      'batch': 'Batch3',
      'year': '2025-2026'},
     {'rollNo': 436,
      'name': 'Aditya Patel',
      'email': 'g22.aditya.patel@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'IT',
      'batch': 'Batch2',
      'year': '2024-2025'},
     {'rollNo': 476,
      'name': 'Aarav Verma',
      'email': 'g22.aarav.verma@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'CS',
      'batch': 'Batch2',
      'year': '2025-2026'},
     {'rollNo': 413,
      'name': 'Vivaan Das',
      'email': 'g22.vivaan.das@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'CS',
      'batch': 'Batch1',
      'year': '2024-2025'},
     {'rollNo': 419,
      'name': 'Kabir Das',
      'email': 'g22.kabir.das@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'CS',
      'batch': 'Batch2',
      'year': '2025-2026'},
     {'rollNo': 479,
      'name': 'Krishna Khan',
      'email': 'g22.krishna.khan@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'IT',
      'batch': 'Batch1',
      'year': '2025-2026'},
     {'rollNo': 408,
      'name': 'Aditya Jain',
      'email': 'g22.aditya.jain@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'IT',
      'batch': 'Batch3',
      'year': '2024-2025'},
     {'rollNo': 453,
      'name': 'Krishna Sharma',
      'email': 'g22.krishna.sharma@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'IT',
      'batch': 'Batch2',
      'year': '2025-2026'},
     {'rollNo': 492,
      'name': 'Ishaan Jain',
      'email': 'g22.ishaan.jain@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'IT',
      'batch': 'Batch1',
      'year': '2024-2025'},
     {'rollNo': 447,
      'name': 'Ishaan Das',
      'email': 'g22.ishaan.das@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'CS',
      'batch': 'Batch1',
      'year': '2025-2026'},
     {'rollNo': 436,
      'name': 'Aarav Patel',
      'email': 'g22.aarav.patel@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'CS',
      'batch': 'Batch3',
      'year': '2025-2026'},
     {'rollNo': 423,
      'name': 'Om Singh',
      'email': 'g22.om.singh@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'IT',
      'batch': 'Batch1',
      'year': '2024-2025'},
     {'rollNo': 498,
      'name': 'Krishna Patel',
      'email': 'g22.krishna.patel@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'IT',
      'batch': 'Batch1',
      'year': '2025-2026'},
     {'rollNo': 468,
      'name': 'Aditya Sharma',
      'email': 'g22.aditya.sharma@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'CS',
      'batch': 'Batch3',
      'year': '2025-2026'},
     {'rollNo': 408,
      'name': 'Vivaan Khan',
      'email': 'g22.vivaan.khan@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'CS',
      'batch': 'Batch1',
      'year': '2024-2025'},
     {'rollNo': 422,
      'name': 'Kabir Gupta',
      'email': 'g22.kabir.gupta@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'IT',
      'batch': 'Batch1',
      'year': '2025-2026'},
     {'rollNo': 446,
      'name': 'Aarav Gupta',
      'email': 'g22.aarav.gupta@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'CS',
      'batch': 'Batch2',
      'year': '2024-2025'},
     {'rollNo': 481,
      'name': 'Krishna Mishra',
      'email': 'g22.krishna.mishra@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'CS',
      'batch': 'Batch3',
      'year': '2025-2026'},
     {'rollNo': 444,
      'name': 'Atharv Sharma',
      'email': 'g22.atharv.sharma@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'IT',
      'batch': 'Batch2',
      'year': '2024-2025'},
     {'rollNo': 486,
      'name': 'Om Das',
      'email': 'g22.om.das@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'CS',
      'batch': 'Batch3',
      'year': '2025-2026'},
     {'rollNo': 418,
      'name': 'Aarav Reddy',
      'email': 'g22.aarav.reddy@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'CS',
      'batch': 'Batch3',
      'year': '2024-2025'},
     {'rollNo': 426,
      'name': 'Vivaan Mishra',
      'email': 'g22.vivaan.mishra@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'IT',
      'batch': 'Batch3',
      'year': '2025-2026'},
     {'rollNo': 477,
      'name': 'Aarav Sharma',
      'email': 'g22.aarav.sharma@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'IT',
      'batch': 'Batch2',
      'year': '2024-2025'},
     {'rollNo': 440,
      'name': 'Rohan Sharma',
      'email': 'g22.rohan.sharma@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'CS',
      'batch': 'Batch2',
      'year': '2025-2026'},
     {'rollNo': 416,
      'name': 'Aarav Jain',
      'email': 'g22.aarav.jain@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'IT',
      'batch': 'Batch2',
      'year': '2024-2025'},
     {'rollNo': 495,
      'name': 'Aarav Singh',
      'email': 'g22.aarav.singh@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'IT',
      'batch': 'Batch1',
      'year': '2024-2025'},
     {'rollNo': 498,
      'name': 'Atharv Das',
      'email': 'g22.atharv.das@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'IT',
      'batch': 'Batch3',
      'year': '2024-2025'},
     {'rollNo': 420,
      'name': 'Kabir Jain',
      'email': 'g22.kabir.jain@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'IT',
      'batch': 'Batch3',
      'year': '2025-2026'},
     {'rollNo': 472,
      'name': 'Aryan Jain',
      'email': 'g22.aryan.jain@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'CS',
      'batch': 'Batch3',
      'year': '2025-2026'},
     {'rollNo': 454,
      'name': 'Aditya Khan',
      'email': 'g22.aditya.khan@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'CS',
      'batch': 'Batch1',
      'year': '2025-2026'},
     {'rollNo': 421,
      'name': 'Atharv Gupta',
      'email': 'g22.atharv.gupta@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'CS',
      'batch': 'Batch1',
      'year': '2025-2026'},
     {'rollNo': 479,
      'name': 'Krishna Reddy',
      'email': 'g22.krishna.reddy@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'IT',
      'batch': 'Batch3',
      'year': '2024-2025'},
     {'rollNo': 436,
      'name': 'Om Khan',
      'email': 'g22.om.khan@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'IT',
      'batch': 'Batch3',
      'year': '2025-2026'},
     {'rollNo': 404,
      'name': 'Aryan Mishra',
      'email': 'g22.aryan.mishra@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'CS',
      'batch': 'Batch2',
      'year': '2024-2025'},
     {'rollNo': 432,
      'name': 'Kabir Khan',
      'email': 'g22.kabir.khan@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'CS',
      'batch': 'Batch3',
      'year': '2024-2025'},
     {'rollNo': 403,
      'name': 'Krishna Jain',
      'email': 'g22.krishna.jain@gnkhalsa.edu.in',
      'role': 'student',
      'department': 'CS',
      'batch': 'Batch1',
      'year': '2024-2025'}
  ];

const connectDB = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log("Connected to MongoDB");

    const bulkOps = students.map(student => ({
      updateOne: {
        filter: { rollNo: student.rollNo },
        update: { $setOnInsert: student }, // Only set if the document does not exist
        upsert: true // Insert if the document doesn't exist
      }
    }));

    const result = await userModel.bulkWrite(bulkOps);
    console.log(`${result.upsertedCount} new student(s) inserted`);
    console.log(`${result.modifiedCount} existing student(s) updated`);
  } catch (error) {
    console.error("Error connecting to MongoDB or updating data:", error);
  }
  DBconnect();
};

export default connectDB;